server {
    listen 80;
    server_name your-domain.com;

    client_max_body_size 100M;

    location /statics/ {
        alias /app/awesomewms/templates/dist/spa/statics/;
    }

    location /assets/ {
        alias /app/awesomewms/templates/dist/spa/assets/;
    }

    location /icons/ {
        alias /app/awesomewms/templates/dist/spa/icons/;
    }

    location /css/ {
        alias /app/awesomewms/templates/dist/spa/css/;
    }

    location /js/ {
        alias /app/awesomewms/templates/dist/spa/js/;
    }

    location /fonts/ {
        alias /app/awesomewms/templates/dist/spa/fonts/;
    }

    location /media/ {
        alias /app/awesomewms/media/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header token $http_token;
        proxy_set_header language $http_language;
        proxy_set_header project $http_project;
    }
}
