[program:wms-server]
command=python bomiot/server/manage.py runserver 0.0.0.0:8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/supervisor_server.log
stderr_logfile=/app/logs/supervisor_server_error.log
user=root
environment=DJANGO_SETTINGS_MODULE="bomiot.server.server.settings"
