# Generated by Django 4.2.29 on 2026-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_team_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Time')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(default='GET', max_length=18, verbose_name='Method')),
                ('api', models.CharField(max_length=255, verbose_name='API API')),
                ('func_name', models.CharField(max_length=255, verbose_name='API Name')),
                ('name', models.CharField(default='', max_length=255, verbose_name='API Description')),
            ],
            options={
                'verbose_name': 'bomiot API',
                'verbose_name_plural': 'bomiot API',
                'db_table': 'bomiot_api',
                'ordering': ['id'],
            },
        ),
    ]
